# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 10s

scrape_configs:
- job_name: statsd_exporter

  metrics_path: '/metrics'

  target_groups:
  - targets: ['promstatsd_statsd_exporter_1:9102']
    labels:
      exporter: 'statsd'
